export const GET_ERRORS = 'GET_ERRORS';
export const GET_CHANNELS_DATA = 'GET_CHANNELS_DATA';
export const SET_NEXTPAGE_TOKEN = 'SET_NEXTPAGE_TOKEN';
export const GET_NEXT_PAGE_DATA = 'GET_NEXT_PAGE_DATA';
export const GET_SEARCH_DATA = 'GET_SEARCH_DATA';
export const SET_LOADING = 'SET_LOADING';
