export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const GET_CHANNELS_DATA = 'GET_CHANNELS_DATA';
export const SET_NEXTPAGE_TOKEN = 'SET_NEXTPAGE_TOKEN';
export const GET_NEXT_PAGE_DATA = 'GET_NEXT_PAGE_DATA';
